language : c++
#compiler :
#    - gcc
#    - clang
os : linux
cache: ccache

matrix:
  include:
     # works on Trusty
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-7
            - ubuntu-toolchain-r-test
          packages:
            - clang-7
            - g++-8
      env:
        - MATRIX_EVAL_GCC='CC=gcc-8 && CXX=g++-8'
        - MATRIX_EVAL="CC=clang-7 && CXX=clang++-7"

before_install:
    - eval "${MATRIX_EVAL_GCC}"
    - export CC CXX
    - ./third-party/install-third-party.sh
    - eval "${MATRIX_EVAL}"
    - export CC CXX

script :
    - mkdir -p _build && cd _build
    - cmake -DENABLE_COVERAGE=ON ..
    - make -j4
    - ctest -j4

after_success:
    - cd _build && bash <(curl -s https://codecov.io/bash) -Z > /dev/null 2>&1
