# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  - group: CODECOV

jobs:
- job: test
  displayName: 'Building and Testing'
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-18.04
  pool:
    vmImage: $(vmImage)

  container: vesoft/nebula-dev:centos7
  timeoutInMinutes: 0

  steps:
  - script: mkdir _build && cd _build && cmake -DCMAKE_CXX_COMPILER=clang++-8 -DCMAKE_C_COMPILER=clang-8 -DENABLE_COVERAGE=ON -DNEBULA_CLANG_USE_GCC_TOOLCHAIN=/opt/vesoft/toolset/gcc/7.5.0 ..
    displayName: 'cmake'

  - script: cd _build && echo -j$(nproc) && make -j$(nproc)
    displayName: 'make'

  - script: cd _build && ctest -j$(nproc)
    displayName: 'test'

  - script: cd _build && bash <(curl -s https://codecov.io/bash) -Z -t $(CODECOV_TOKEN) > /dev/null 2>&1
    displayName: 'coverage'
