# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  - group: CODECOV

jobs:
- job: test
  displayName: 'Building and Testing'
  strategy:
    matrix:
      Linux:
        vmImage: ubuntu-18.04
  pool:
    vmImage: $(vmImage)

  container: vesoft/nebula-dev:ubuntu1804
  timeoutInMinutes: 0

  steps:
  - script: mkdir _build && cd _build && cmake -DCMAKE_CXX_COMPILER=clang++-8 -DCMAKE_C_COMPILER=clang-8 -DENABLE_COVERAGE=ON -DNEBULA_CLANG_USE_GCC_TOOLCHAIN=/opt/vesoft/toolset/gcc/7.5.0 ..
    displayName: 'cmake'

  - script: cd _build && make -j$(expr $(nproc) \* 2)
    displayName: 'make'

  - script: cd _build && ctest -j$(nproc)
    displayName: 'test'

  - script: |
      apt-get update -y && apt-get install -y lcov
      cd _build
      lcov --capture --gcov-tool /opt/vesoft/toolset/gcc/7.5.0/bin/gcov --directory . --output-file coverage.info
      bash <(curl -s https://codecov.io/bash) -t $(CODECOV_TOKEN) -f coverage.info
    displayName: 'coverage'
