name: tools

on:
  schedule:
    - cron: '0 18 * * *'

jobs:
  docker:
    name: build tools docker image
    runs-on: ubuntu-18.04
    steps:
      - uses: azure/container-actions/docker-login@master
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: build
        env:
          IMAGE_NAME: ${{ secrets.DOCKER_USERNAME }}/spark-sstfile-generator:nightly
        run: |
          docker build -f src/tools/spark-sstfile-generator/Dockerfile -t ${IMAGE_NAME} .
          docker push ${IMAGE_NAME}
        shell: bash
